apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-service-helm.fullname" . }}-deployment
  labels:
    app: {{ .Values.service.name }}
  {{- include "order-service-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
    {{- include "order-service-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
      {{- include "order-service-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ $.Values.deployment.orderService.image.repository }}:{{ $.Values.deployment.orderService.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.orderService.imagePullPolicy }}
        ports:
          - name: {{ .Values.service.name }}
            containerPort: 8080
      imagePullSecrets:
      - name: regcred