apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "item-service-helm.fullname" . }}-deployment
  labels:
    app: {{ .Values.service.type }}
  {{- include "item-service-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.type }}
    {{- include "item-service-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.type }}
      {{- include "item-service-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.deployment.itemService.image.repository }}:{{ .Values.deployment.itemService.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.deployment.itemService.imagePullPolicy }}
        name: {{ .Values.service.type }}
        ports:
        - containerPort: 8080
          name: {{ .Values.service.type }}
        resources: {}
      imagePullSecrets:
      - name: regcred