apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "item-service.fullname" . }}
  labels:
    app: {{ .Values.service.name }}
  {{- include "item-service.labels" . | nindent 4 }}
    resource: {{ .Values.labels.resource }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
    {{- include "item-service.selectorLabels" . | nindent 6 }}
      resource: {{ .Values.selector.matchLabels.resource }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
      {{- include "item-service.selectorLabels" . | nindent 8 }}
        resource: {{ .Values.template.metadata.labels.resource }}
    spec:
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ $.Values.deployment.itemService.image.repository }}:{{ $.Values.deployment.itemService.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.itemService.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
          - name: {{ .Values.service.name }}
            containerPort: 8080
      imagePullSecrets:
      - name: regcred