namespace: app
deployment:
  orderService:
    image:
      repository: 829721034047.dkr.ecr.ap-northeast-2.amazonaws.com/order-service
      tag: 1.0.23
    imagePullPolicy: Always
kubernetesClusterDomain: cluster.local

service:
  name: order-service
  ports:
  - port: 8080
    targetPort: 0
  type: ClusterIP
  selector:
    resource: cpu

labels:
  resource: cpu

selector:
  matchLabels:
    resource: cpu

template:
  metadata:
    labels:
      resource: cpu

resources:
  requests:
    cpu: 800m
  limits:
    cpu: 1000m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
