namespace: app
deployment:
  orderService:
    image:
      repository: 829721034047.dkr.ecr.ap-northeast-2.amazonaws.com/order-service
      tag: 1.0.23
    imagePullPolicy: Always
  readinessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
kubernetesClusterDomain: cluster.local

service:
  name: order-service
  ports:
    - port: 8080
      targetPort: 0
  type: ClusterIP
  selector:
    resource: cpu

labels:
  resource: cpu

selector:
  matchLabels:
    resource: cpu

template:
  metadata:
    labels:
      resource: cpu

resources:
  requests:
    cpu: 1200m
    memory: 1000Mi
  limits:
    cpu: 1500m
    memory: 2000Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
