apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "user-service.fullname" . }}
  labels:
    app: {{ .Values.deployment.name }}
  {{- include "user-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
    {{- include "user-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
      {{- include "user-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ $.Values.deployment.userService.image.repository }}:{{ $.Values.deployment.userService.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.userService.imagePullPolicy }}
        ports:
          - name: {{ .Values.service.name }}
            containerPort: 8080
      imagePullSecrets:
      - name: regcred