namespace: app
deployment:  
  itemService:
    image:
      repository: 829721034047.dkr.ecr.ap-northeast-2.amazonaws.com/item-service
      tag: 1.0.15
    imagePullPolicy: Always
  replicas: 1
kubernetesClusterDomain: cluster.local

service:
  name: item-service
  ports:
  - port: 8080
    targetPort: 0
  type: ClusterIP
  selector:
    resource: cpu

labels:
  resource: cpu

selector:
  matchLabels:
    resource: cpu

template:
  metadata:
    labels:
      resource: cpu

resources:
  requests:
    cpu: 600m
  limits:
    cpu: 800m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80