namespace: app
deployment:
  itemService:
    image:
      repository: 829721034047.dkr.ecr.ap-northeast-2.amazonaws.com/item-service
      tag: 1.0.19
    imagePullPolicy: Always
  replicas: 2
kubernetesClusterDomain: cluster.local

service:
  name: item-service
  ports:
    - port: 8080
      targetPort: 0
  type: ClusterIP
  selector:
    resource: cpu

labels:
  resource: cpu

selector:
  matchLabels:
    resource: cpu

template:
  metadata:
    labels:
      resource: cpu

resources:
  requests:
    cpu: 1200m
    memory: 1000Mi
  limits:
    cpu: 1500m
    memory: 1500Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  # targetMemoryUtilizationPercentage: 40
  targetCPUUtilizationPercentage: 60
