apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "order-service.fullname" . }}
  labels:
  {{- include "order-service.labels" . | nindent 4 }}
    resource: {{ .Values.labels.resource }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.name }}
  {{- include "order-service.selectorLabels" . | nindent 4 }}
    resource: {{ .Values.service.selector.resource }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}